[build]
  # Directory where Netlify Functions are located
  functions = "netlify/functions"
  
  # Directory to publish (your root since index.html is there)
  publish = "."
  
  # Build command (none needed for static site)
  command = ""

[build.environment]
  SECRETS_SCAN_SMART_DETECTION_OMIT_VALUES = "AIzaSyCV-awjx4Qa0OWgQlT8bbYaxjLEawWfu7s"

# Redirect API calls to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback (optional, for client-side routing)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false